mindsdb/lightwood

- docs/examples/home_rentals.py
- lightwood/__init__.py
- lightwood/api/data_source.py
- lightwood/encoders/__init__.py
- created a list of default encoders that can be used when building a configuration file
> default encoders

- .gitignore
- docs/docs/API.md
- docs/docs/index.md
Minor typos fixed int the documentation.
> Docs update

- .travis.yml
- MANIFEST.in
- install.sh
- lightwood/__about__.py
- setup.py
> Publishing changes

- lightwood/__about__.py
- lightwood/encoders/numeric/numeric.py
Fix to account for nan in NumericEncoder
> account for nan in NumericEncoder

- lightwood/__about__.py
- lightwood/encoders/image/helpers/nn.py
- lightwood/encoders/image/img_2_vec.py
- requirements.txt
Allow urls to be used to image instead of paths
> Img from url

- lightwood/__about__.py
- lightwood/api/predictor.py
- lightwood/encoders/image/helpers/img_to_vec.py
- lightwood/encoders/image/img_2_vec.py
- lightwood/mixers/nn/nn.py
- tests/ci_tests/full_test.py
* Version update to 0.9.
* Stop conditions for NN training reduced to time-based condition and convergence condition (error on testing dataset getting on average worst over the last 5-10 runs).
* Fixed and issue where Image Encoder was not sourcing & using the device (as in gpu or cpu) properly. 
* Fixed an issue where the model was being pickled with GPU-load tensors on cuda-enabled machines and thus unpickling on a CPU-only machine was not possible
* Changes the way `test_accuracy` is computed to reflect the algorithm being used and passing it to the callback function when doing training iterations over the dataset
> Release 0.9

- docs/examples/home_rentals.py
- lightwood/api/data_source.py
- lightwood/encoders/categorical/categorical.py
- lightwood/encoders/datetime/datetime.py
- lightwood/encoders/image/img_2_vec.py
- lightwood/encoders/image/nn.py
- lightwood/encoders/numeric/numeric.py
- lightwood/encoders/text/infersent.py
- lightwood/encoders/text/rnn.py
- lightwood/encoders/time_series/cesium_ts.py
* Change all the encoders to add a `fit` function that adapts them to a dataset, rather than doing so as part of the first call to `encode`.
* Also added better handling of `None` in numerical and text encoders.
* Simplified encoders a bit
Progress towards #6 
Resolves #41 
Resolves #29
> Better encoding

- lightwood/__about__.py
- lightwood/api/data_source.py
- lightwood/data_schemas/predictor_config.py
- lightwood/encoders/numeric/numeric.py
- lightwood/mixers/nn/helpers/transformer.py
- tests/ci_tests/full_test.py
* Enables encoder cache disabling, thus solving #30 
* Some fixes to dropout which was *still* not working correctly (at this point I've debugged it to death and I'm pretty certain it works 100% the way we want it to)
* Some cleanup of the logic inside the data source
> Encoder cache disabling

- .travis.yml
> Add py version to choco install

- lightwood/__about__.py
- lightwood/api/data_source.py
- lightwood/api/predictor.py
- lightwood/config/config.py
- lightwood/mixers/nn/nn.py
- tests/ci_tests/full_test.py
Added option for lightwood to handle unbalanced dataset via over sampling.
Minor changes:
* Using the mean of all other weights as the default weight for values not present in the weight map.
* Arranged and commented config flags
> Oversample

- lightwood/__about__.py
- lightwood/api/predictor.py
- tests/ci_tests/full_test.py
Dynamically setting the `stop_training_after_seconds` variable based on dataset size.
> Dynamic stop training limit

- lightwood/__about__.py
- lightwood/encoders/text/distilbert.py
Note: Don't merge yet, just here so we can more easily discuss it. It won't break anything, it "works", at least based on the unit tests, but the accuracy of the predictions is awful at the moment.
Added a "head" to the DistilBERT text encoder that can be trained to try and predict an arbitrary combination or numeric and categorical output, for cases when the target is not a single category and thus we can't use the actual model.
> Text to number

- lightwood/api/gym.py
- lightwood/api/predictor.py
- lightwood/encoders/categorical/autoencoder.py
Hello~
I'm currently reviewing your great project, and fixed some typo in comment.
Please check.
Thanks.
> Fix comment typo

- .travis.yml
* Ignore Doc change #109
* Fail travis build for errors in scripts (unit tests) #110
@George3d6 This is just the same replication from mindsdb/mindsdb and I think will be useful as I was going through Lightwood
> Improvements to Travis

- lightwood/__about__.py
- lightwood/api/predictor.py
- lightwood/config/config.py
- lightwood/mixers/boost/boost.py
- lightwood/mixers/nn/nn.py
- tests/ci_tests/ci_tests.py
* Added weight to gradient boosting helper mixer when predicting unbalanced categories
* Added weight to error function when applied to unbalanced categories
* Made boosting mixer training mandatory (maybe consider not doing this ? Or doing so only for datasets bellow a certain size ?), as it usually takes little time and there's a chance they perform when the network utterly fails to get us anything.
> Weight balancing forst booster and accuracy function

- lightwood/__about__.py
- lightwood/config/config.py
- lightwood/encoders/time_series/ts_fresh_ts.py
- requirements.txt
Improvements to TsFresh Timeseries Encoder
> Improvements to TsFresh Timeseries Encoder

- lightwood/__about__.py
- lightwood/api/predictor.py
- lightwood/mixers/nn/nn.py
* Updating optimizer parameters when updating the model
* Logging more information
* Made the evaluate every epoch logic a bit more streamlined and fixed a bug where there was an "evaluation luul" between each subset iteration
* Fixed a bug where the selfaware network was being disabled multiple times in a row
* Passing the `lr` to the optimizer explicitly so that we can more easily switch Ranger with the standard torch optimizers
> Various fixes

- docs/examples/learn_to_multiply.py
- lightwood/api/predictor.py
- lightwood/mixers/helpers/default_net.py
- lightwood/mixers/helpers/ranger.py
- lightwood/mixers/nn/nn.py
Fixed a bug where rectifiers were not being added to the structure of the selfaware network.
Also removed some unused code and added a few metrics to the learn to multiply test.
> Selfaware fix

- lightwood/__about__.py
- lightwood/api/predictor.py
- lightwood/mixers/helpers/default_net.py
- lightwood/mixers/nn/nn.py
- lightwood/model_building/__init__.py
- optional_requirements.txt
- requirements.txt
Fixed model transfer from/to GPU and made it in such a way as to account for DataParallel usage.
> Gpu to cpu fixes

- lightwood/__about__.py
- lightwood/encoders/image/helpers/img_to_vec.py
- lightwood/encoders/image/img_2_vec.py
Fixed an issue where the image encoder network was not being but in eval mode, also added `torch.no_grad` to speedup the process
> Image encoder fix

- docs/examples/learn_to_classify.py
- tests/dropout/test_dropout.py
This closes #164, will probably auto-merge since there's not breaking change in here, it's just added tests and some fixes to the existing tests that are run automatically.
> Test suite to evaluate predictions with missing column

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
This PR simplifies the bug report template and include a simple template for pull requests.
> Add Gh templates

- lightwood/api/data_source.py
Currently this check always fails, this fixes it
> Fix training data in prepare_encoder args check

- lightwood/api/predictor.py
- lightwood/encoders/__init__.py
- lightwood/encoders/audio/amplitude_ts.py
- lightwood/encoders/categorical/autoencoder.py
- lightwood/encoders/categorical/onehot.py
- lightwood/encoders/datetime/datetime.py
- lightwood/encoders/encoder_base.py
- lightwood/encoders/image/img_2_vec.py
- lightwood/encoders/image/nn.py
- lightwood/encoders/numeric/numeric.py
- lightwood/encoders/text/distilbert.py
- lightwood/encoders/text/infersent.py
- lightwood/encoders/text/rnn.py
- lightwood/encoders/text/tfidf.py
- lightwood/encoders/time_series/cesium_ts.py
- lightwood/encoders/time_series/rnn.py
- lightwood/encoders/time_series/ts_fresh_ts.py
Resolves https://github.com/mindsdb/lightwood/issues/202
> base encoder

- lightwood/api/predictor.py
- lightwood/encoders/categorical/multihot.py
- tests/unit_tests/encoders/categorical/test_multihot_encoder.py
To be merged after: multihot-handle-none
> Use F1 score to evaluate multiple categories score

- lightwood/api/data_source.py
- lightwood/constants/lightwood.py
- lightwood/encoders/__init__.py
- lightwood/encoders/text/__init__.py
- lightwood/encoders/text/flair.py
- requirements.txt
* This resolves #196 by adding a flair based encoder, not making this the default since I see no advantage over our standard BERT based encoder
* Also added short text type and exported text encoders in the places where they had to be exported
> Encode with flair

- lightwood/encoders/numeric/numeric.py
- tests/unit_tests/encoders/text/test_short_text_encoder.py
* Some fixes to the numeric encoder, one simplification and one to fix a bug that was actually pretty major and didn't allow it to properly work with negative numbers
* Spelling fix from `vocavb` to `vocab`
> Small fixes

- lightwood/encoders/categorical/autoencoder.py
- lightwood/mixers/helpers/default_net.py
- lightwood/mixers/helpers/selfaware.py
- lightwood/mixers/nn/nn.py
Very early implementation that separates the self-aware network from the main NN into its own module to have a training loop where each one has its separate optimizer. See #217. Testing and benchmarking is still pending.
> [WIP] Separate Self-Aware

- lightwood/mixers/helpers/selfaware.py
- lightwood/mixers/nn/nn.py
> Minor self-aware cleanup

- lightwood/encoders/time_series/rnn.py
- Added time series maximum length detection, replacing default value
- Increased default batch_size
> Time series RNN optimizations

- lightwood/__about__.py
- Remove logic around copying the best model that was linked to the selfaware network's status.
> Release 0.38

- lightwood/__about__.py
- lightwood/encoders/text/distilbert.py
- tests/unit_tests/encoders/text/test_distilbert.py
- Hotfix in DistilBERT call to DefaultNet. Solves MindsDB issue [#671](https://github.com/mindsdb/mindsdb/issues/671).
> Release 0.39

- lightwood/api/predictor.py
- lightwood/encoders/__init__.py
- lightwood/encoders/audio/amplitude_ts.py
- lightwood/encoders/categorical/autoencoder.py
- lightwood/encoders/image/nn.py
- lightwood/encoders/numeric/numeric.py
- lightwood/encoders/text/distilbert.py
- lightwood/encoders/text/infersent.py
- lightwood/encoders/text/rnn.py
- lightwood/logger/__init__.py
- lightwood/logger/logger.py
- lightwood/mixers/helpers/default_net.py
- lightwood/mixers/helpers/shapes.py
- lightwood/mixers/nn/nn.py
- lightwood/mixers/sk_learn/sk_learn.py
- scraps/bayesian_nn/bayesian_nn.py
- scraps/mixer_with_gym_incomplete.py
- tests/unit_tests/encoders/categorical/test_autoencoder.py
1. logging to 'root' logger changed to logger with name 'lightwood.{pid}'
2. when logger initialised it try read log_level from env. That allows control log level same way as in mindsdb_native now.
> Logging changes

- lightwood/api/data_source.py
- lightwood/encoders/datetime/datetime.py
- lightwood/encoders/encoder_base.py
- lightwood/encoders/time_series/helpers/rnn_helpers.py
- lightwood/encoders/time_series/rnn.py
- tests/unit_tests/encoders/date/test_datetime.py
- tests/unit_tests/encoders/time_series/test_rnn.py
Addresses #170. 
- Deploys the new normalizers for numeric data and datetime data in the timeseries encoder. 
- Fix a few bugs in the encoder itself
- Slightly change how to operate the datetime encoder sinusoidal mode
- Renamed internal methods in MinMaxNormalizer
> Time series normalize by type

- lightwood/api/data_source.py
- lightwood/api/predictor.py
- lightwood/data_schemas/predictor_config.py
- lightwood/mixers/__init__.py
- lightwood/mixers/base_mixer.py
- lightwood/mixers/boost.py
- lightwood/mixers/nn.py
- lightwood/mixers/sklearn_mixer.py
- tests/unit_tests/mixers/test_boost.py
- tests/unit_tests/test_predictor.py
- Add support for tags data type in `SklearnMixer`
- FIx schema of `depends_on_column` key in column config
> fix mixers for tags

- lightwood/__about__.py
- lightwood/api/data_source.py
- lightwood/data_schemas/predictor_config.py
- lightwood/encoders/time_series/helpers/rnn_helpers.py
- lightwood/encoders/time_series/rnn.py
- lightwood/mixers/nn.py
- tests/unit_tests/encoders/time_series/test_rnn.py
- Added support for categorical target in time series encoder
> Release 0.45

- lightwood/__about__.py
- lightwood/api/data_source.py
- Changed autoregressive column naming scheme from `previous_` to `__mdb_ts_previous_`
> Release 0.48

- lightwood/api/predictor.py
- requirements.txt
> Stop using pickle

- lightwood/encoders/text/distilbert.py
The maximum length supported by each Transformer model was not being retrieved properly. The PR fixes this, which in turn should solve [#984](https://github.com/mindsdb/mindsdb/issues/984)
> Fix DistilBERT input truncation

- .github/workflows/cla.yml
- lightwood/__about__.py
This PR adds CLA automation for new contributors to Lightwood.
> Add cla bot

- lightwood/mixers/lightgbm.py
* Training ordinal encoders on train data, always
* Fixed train/test iteration order
* Creating datasets twice to avoid weird optuna related error
> Lightgbm fixes

- lightwood/__about__.py
- lightwood/mixers/lightgbm.py
Needed for confidence estimation to work in Native
> hotfix: lightgbm mixer belief distribution 

- lightwood/__about__.py
- lightwood/mixers/lightgbm.py
> hotfix: add class labels in lightgbm mixer

- lightwood/mixers/lightgbm.py
Checking if the GPU version of lightgbm is installed, kind of a hacky way to do it, asked here for a better variant: https://github.com/microsoft/LightGBM/issues/3939 ... but it's good enough.
If it's installed, use that + tweak a parameter based on the official docs recommendation (though maybe designed for older GPUs ... ? Should we bin numbers at all on GPUs ? Can lightgbm not bin numbers and determine values to split at on a continous axis? Doesn't seem to be the case but idk)
> checking for and using gpu

- lightwood/api/data_source.py
Closes https://github.com/mindsdb/lightwood/issues/327
> Create weights for multiclass

- lightwood/helpers/device.py
- lightwood/mixers/helpers/default_net.py
> Round robin GPUs

- .github/workflows/ligthtwood.yml
- lightwood/__about__.py
- lightwood/helpers/device.py
- pyproject.toml
- setup.py
Changelog:
- Handle unknown validation dataset target columns values in LightGBM mixer (#405)
- Positive domain handling for LightBGM mixer (#403)
> Release 0.62.0

- lightwood/__about__.py
- requirements.txt
Capped NumPy due to Optuna requirements
> hotfix: numpy < 1.20.0

- lightwood/helpers/torch.py
- lightwood/mixers/nn.py
- Fairly minor fix for correctly using AMP with our self-aware neural network in the NnMixer
> Fixes for self-aware AMP usage

- lightwood/__about__.py
- requirements.txt
- Remove Torch 1.8.0 as requirement due to issue on their end (#53336) that was fixed in 1.8.1
> Hotfix 0.64.1

- lightwood/__about__.py
Changelog:
- Improved LightGBM mixer time budgeting when using Optuna (#426)
> Release 0.65.0

- lightwood/mixers/lightgbm.py
- requirements.txt
> Optuna -> 2.8.0

- lightwood/__about__.py
- lightwood/__init__.py
- lightwood/helpers/device.py
Changelog:
- Bumps Optuna to 2.8.0 release, LightGBM mixer is now reproducible.
> Release 0.68.0

- lightwood/api/predictor.py
- lightwood/encoders/audio/amplitude_ts.py
- lightwood/mixers/boost.py
- lightwood/mixers/lightgbm.py
- lightwood/mixers/sklearn_mixer.py
- Enable GPU-trained model usage in non-CUDA machines (added .to() method to non-NN mixers for this)
- Fix small import bug in audio encoder
> Enable GPU-trained model loading in non-CUDA machines

- lightwood/helpers/text.py
very useful inside lightwood and mindsdb to avoid repeating code with importlib
> Predictor from code string helper function

- lightwood/api/json_ai.py
- lightwood/encoder/__init__.py
- lightwood/encoder/array/array.py
- lightwood/encoder/base.py
- lightwood/encoder/categorical/autoencoder.py
- lightwood/encoder/numeric/ts_numeric.py
- lightwood/encoder/text/pretrained.py
- lightwood/encoder/time_series/rnn.py
- requirements.txt
- tests/integration/advanced/test_custom_modules.py
If the user overrides a hidden module, but doesn't pass all of the arguments **and** if we detect some of the argument names for this module are the same as the "default" argument names, we'll implicitly pass them.
> Passing default arguments

- lightwood/api/high_level.py
- lightwood/api/json_ai.py
- lightwood/data/cleaner.py
- lightwood/data/statistical_analysis.py
- requirements.txt
Fix for #560 and hopefully better able to run with more pandas versions... let's see if tests pass
> Fix cleaner 2

- lightwood/encoder/image/helpers/img_to_vec.py
- lightwood/encoder/image/img_2_vec.py
> Revert "fix: fixes missing torchvision import"

- lightwood/analysis/analyze.py
- lightwood/analysis/nc/calibrate.py
- lightwood/api/json_ai.py
- lightwood/api/types.py
- lightwood/data/timeseries_transform.py
- lightwood/helpers/general.py
- lightwood/helpers/ts.py
- tests/integration/advanced/test_timeseries.py
- tests/integration/basic/test_model_selection.py
Closes #793. Follows naming scheme used in MindsDB.
Self-explanatory.
> Rename time series "nr_predictions" to "horizon"

- lightwood/mixer/sktime.py
If the user wants to check in-sample forecasts, the corresponding offset argument should be set to minus the amount of training data points that were fed. However, an exception will be raised if this value is incorrectly set _or_ if the model applies differencing and the user does not account for this. This PR checks and guards this so that in-sample forecasts start from the correct minimum start point.
Simple bound checking inside the `__call__` method.
> Fix: limit lowest possible relative forecasting offset (sktime mixer)

- lightwood/analysis/nc/calibrate.py
- lightwood/analysis/nc/util.py
- lightwood/api/types.py
- tests/integration/advanced/test_timeseries.py
> Remove `anomaly_error_rate` arg in favor of `fixed_confidence`

- lightwood/analysis/helpers/acc_stats.py
Simple PR that removes some unused code inside the `AccStats` analysis block.
> Clean up acc_stats

- lightwood/mixer/neural.py
Fix "IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed". 
#851
> Fix dimension error

- lightwood/__about__.py
- lightwood/api/types.py
- setup.py
> Release 22.6.1.1

- lightwood/analysis/explain.py
- lightwood/api/json_ai.py
- lightwood/data/timeseries_analyzer.py
- lightwood/encoder/time_series/helpers/common.py
- lightwood/helpers/general.py
- lightwood/helpers/ts.py
- lightwood/mixer/lightgbm_array.py
- lightwood/mixer/sktime.py
- tests/unit_tests/helpers.py
- tests/utils/timing.py
To offer an additional tool that forecasting mixers may choose to use.
- Refactored time series analysis module abstractions to have better interfaces
- Moved TS analysis to after data split phase
- Added `Differencer` utility class
NOTE: the PR does not add these into any mixer yet.
> Time series differencing

- setup.py
Deprecate the 3.6 version of Python
> Change supported Python version

- requirements_prophet.txt
https://github.com/facebook/prophet/issues/2181#issuecomment-1166057319
> Use `prophet` 1.1 with wheels

- docssrc/source/index.rst
Fix [#942 ](https://github.com/mindsdb/lightwood/issues/942)
Updated bug found on quick start guide at line 119.
> fix quick start guide

- lightwood/analysis/helpers/feature_importance.py
To compute permutation feature importance in a timely manner if a dataset is too big (in either # of rows or cols)
Minor changes to the block and its interface to accomplish the above behavior. By default, a limit of 1000 rows and 10 columns is applied, but this can be customized (or set both limits to `0` to disable them).
> [Fix] Add data limits to PFI block

- lightwood/api/json_ai.py
- lightwood/api/types.py
- lightwood/data/statistical_analysis.py
Fixes #884
Stored the original amount of columns when generating JsonAI instance.
> Added original amount of columns 

- README.md
Fixes: https://github.com/mindsdb/lightwood/issues/1012
> lightwood currently supports python >=3.7,<3.10

- lightwood/mixer/sktime.py
- tests/integration/advanced/test_timeseries.py
> fix: workaround for StatsForecastAutoARIMA

- lightwood/analysis/helpers/conf_stats.py
- lightwood/analysis/nc/calibrate.py
- lightwood/mixer/gluonts.py
Improves stability and performance of the GluonTS mixer.
- Mixer now handles edge case for new groups (unseen at training time) gracefully.
- ICP block does not fit for any mixer that already produces bounds and confidence estimations.
- Some small fixes in the ConfStats block.
> [fix] gluonts improvements

- lightwood/mixer/random_forest.py
improved the parameter optimization module and made simple adjustments to the code.
> improve random forest mixer

- lightwood/mixer/random_forest.py
Parameter optimization is not effective.
> Bug fix: parameters to be optimized

- tests/integration/advanced/test_timeseries.py
More tests is always better. In particular, this is in response to #1040 so that we actively monitor this edge case.
Add a loop that checks for `horizon \in {1, 4}`
> [test] Improve time series test

- lightwood/mixer/gluonts.py
To enable finer control over the type of distributions that the underlying models learn to fit.
Simple JsonAI-compatible modification to the interface so that any GluonTS `DistributionOutput` instance can be passed to override the default value, for example:
```python
json_ai.model['args']['submodels'] = [
{
"module": "GluonTSMixer",
"args": {
"distribution_output": "'neg_binomial.NegativeBinomialOutput'"
}
},
]
```
> [ENH] Custom output distributions in GluonTS mixer

- lightwood/analysis/nc/calibrate.py
- lightwood/analysis/nc/util.py
> [fix] anomaly false when no actual is available

- lightwood/data/timeseries_transform.py
> [fix] off-by-one length in prev TS target column

- lightwood/helpers/ts.py
- tests/integration/advanced/test_timeseries.py
> [fix] Add multipliers to freq inference

- lightwood/api/json_ai.py
- lightwood/mixer/__init__.py
- lightwood/mixer/xgboost.py
- requirements.txt
- tests/integration/basic/test_model_selection.py
- tests/integration/basic/test_regression.py
> [feat] XGBoost mixer

- lightwood/api/json_ai.py
> [feat] Store global insights inside predictor object

- lightwood/__about__.py
- requirements.txt
This solves some internal issues in e.g. the TS analyzer module.
> fix: bump sktime 0.14.0

- lightwood/__about__.py
- requirements.txt
- Upper version bounds for `type_infer`, `dataprep_ml` & `mindsdb_evaluator` packages
> Hotfix 23.1.2.1

- lightwood/api/json_ai.py
- lightwood/helpers/text.py
> [fix] Improved nltk messaging and check for no available mixers

- lightwood/api/json_ai.py
- lightwood/mixer/__init__.py
- lightwood/mixer/neural.py
- lightwood/mixer/tabtransformer.py
- requirements.txt
- requirements_extra.txt
- tests/unit_tests/mixer/test_tabtransformer.py
To extend the current mixer offering.
TabTransformers in particular seem like a good NN-based approach that we've wanted to integrate with for a while (this "fixes" #926). References: [[1](https://arxiv.org/pdf/2012.06678.pdf)], [[2](https://arxiv.org/pdf/2106.11959v2.pdf)].
Using the nice implementation provided in `tab-transformer-pytorch` ([link](https://github.com/lucidrains/tab-transformer-pytorch/)), we can integrate and leverage scaffolding that already exists for the `Neural` mixer.
> [feat] TabTransformers mixer

- requirements.txt
With pandas >= 1.5.0 we got recursion error for some datasets:
https://github.com/pandas-dev/pandas/issues/45725
> Bound pandas requirement

- .github/workflows/release.yml
- lightwood/__about__.py
- requirements.txt
N/A
- #1125 
- fix evaluator dependency
- add workflow for hotfix releases
> Release 23.4.3.0

- requirements.txt
Black had in issue https://github.com/psf/black/issues/1143
Last version does not have it.
> Fix `black` version

- lightwood/api/json_ai.py
- lightwood/helpers/parallelism.py
This fixes [MDB#6562](https://github.com/mindsdb/mindsdb/issues/6562).
> [fix] More code formatter checks

- lightwood/data/timeseries_transform.py
- Vectorized `__make_predictions` setting
- Remove a slow, old & unused bit of code in the TS transformer
> [enh] Vectorized `__make_predictions` in TS transforms

- lightwood/mixer/nhits.py
Note: impact is mostly on the accuracy, not runtime.
> feat: efficient nhits finetune

- lightwood/api/json_ai.py
> [fix] Abort if there are no valid input features

- lightwood/analysis/nc/calibrate.py
- lightwood/api/json_ai.py
- lightwood/helpers/general.py
> [fix] additional checks for categorical TS

- lightwood/mixer/sktime.py
> [fix] Check horizon in SkTime mixer

- lightwood/mixer/base.py
- lightwood/mixer/unit.py
> [Docs] Add documentation for Unit mixer

- poetry.lock
- pyproject.toml
Merges #1214 and #1215, while ignoring #1216 and #1217
> [Maint] Bump black and pillow

- pyproject.toml
> Update pyproject.toml to bump version

- .github/workflows/doc_build.yml
> Fix doc build
