lightwood/api/data_source.py
lightwood/encoders/image/helpers/img_to_vec.py
lightwood/encoders/image/img_2_vec.py
requirements.txt

* Fixed a bug where `encoder_attrs` weren't passed correctly
* Added an `aim` element (can be passed as part of `encoder_attrs`) for image_to_vec that can be specified as `speed`, `balance` or `accuracy` based on which we can pick an underlying encoder (maybe factoring in additional info about the user's GPU, RAM and CPU in cases where GPU is missing or disabled)
* Added two new pre-trained models to serve as encoders/backbone for images, resnext50 and mobilenet v2. The laters performance is surprisingly poor (slightly slower and slightly less accurate than resnet18, the former yields amazing performance, at least on a sample of the cifrar 100 dataset, but makes training take forever).
In the future I will experiment with different resnext models or maybe increasing the window size of the …

New encoder

---

lightwood/api/predictor.py
lightwood/mixers/nn/helpers/default_net.py
lightwood/mixers/nn/nn.py

* Added a new MLP mixer which seems to yield better or similar performance on existing datasets and is currently used when the input is > 3000 values. The purpose of this is to allow running datasets where input features are encoded into very long input tensors. This reduced training for the non-public dataset we were concerned about (see slack) from 2+ days and counting to ~20 minutes.
* Added an argument to `.learn` that allows us to stop training after a given number of second (the argument is `stop_training_after_seconds` and defaults to 5 days)
* Added a condition that allows the model to stop training in the edge case where it happens to get close to 100% performance on both the train and test datasets.
* Added a condition that allows the model to stop training if no new lowest …

New MLP mixer

---

lightwood/encoders/text/helpers/rnn_helpers.py
lightwood/encoders/text/rnn.py

Allow the RNN encoder&decoder for text to deal with arbitrary length input (was capped at 100 before), the max_length of a sequence is now equal to the biggest example in the training set.
If longer inputs are received in the testing set or when predict is called, the end of the sequence is simply ignored.
Note: Maybe we should consider making it longest example in the training set `*1.2` or something similar, in case we then receive even longer inputs.

RNN decoder&encoder fix

---

.travis.yml
README.md
lightwood/__about__.py
lightwood/__init__.py
lightwood/version.py
setup.py
tests/ci_tests/full_test.py

* Added CI test and a .travis config to run it on all supported platform (could be useful to also add python 3.6 and 3.5 on linux if we wish to support them)
* Added platform specific dependencies in setup.py to allow the install to work on windows and linux.
* Removed a way of sourcing the version in setup.py which would cause a fresh install via pip3 install -e . to fail (since a dependency required to import the file in which the version resided needed to be installed beforehand).
* Added buttons for version & tests to README

CI tests & Install fix

---

.travis.yml
docs/docs/index.md
lightwood/__about__.py
lightwood/__init__.py
setup.py

* Docs are auto publish when tests pass after a merge/PR into master
* Pip version is auto published when tests pass after a merge/PR into master
* Only publishing `sdist` (distribution from source) to pip in order to force `setup.py` to and be able to source dependencies dynamically and run other install scripts that way. 
Note:
We should consider going back to wheels once we can build them on multiple environments, but for now I don't think it's worth it, since we don't have any custom C extension (which is the main selling point for wheel anyway, as far as I can see)

Publishing changes

---

lightwood/__about__.py
lightwood/__init__.py
lightwood/api/predictor.py
lightwood/config/config.py
lightwood/encoders/numeric/numeric.py
lightwood/mixers/nn/helpers/adamw.py
lightwood/mixers/nn/helpers/default_net.py
lightwood/mixers/nn/helpers/shapes.py
lightwood/mixers/nn/nn.py
lightwood/mixers/sk_learn/sk_learn.py
tests/ci_tests/full_test.py

* The `USE_CUDA` config option is now properly used to train the model on the GPU (when true) and on the CPU (when false). Default value is `False` when no GPU is detected and `True` when a GPU is detected.
* Updated and cleaned up the Sklearn mixer (it wasn't working before), it can now be specified from the config
* Added some fundamental building blocks for automatically constructing basic FCNN shapes
* Generating the basic FCNN in `default_net` based on the size of the input/output
* Added AdamW and training with an lr curve using  AdamW (currently disabled but can be enabled via setting the `adamw` flag to `True`). This seemed to increase training speed and sometimes even accuracy on some models, but I won't enable it for now, introducing this into production might happen after a …

Run on cpu

---

.travis.yml
lightwood/__about__.py
setup.py

Installation fix to allow windows to work with pytroch 1.2.0 and torchvision 0.4.0 and to allow both python 3.7 and 3.6 to properly work on windows with lighwood.

Installation fix

---

lightwood/__about__.py
lightwood/api/predictor.py
lightwood/config/config.py
lightwood/encoders/image/helpers/img_to_vec.py
lightwood/mixers/nn/helpers/default_net.py
tests/ci_tests/full_test.py

Added variable in the CONFIG that allows us to specify what GPU to use. Variable is called `Specify what GPU to use` and is a string, the values that should be usually given are `cuda:0`, `cuda:1`... etc, where the number is the number of the GPU.
Resolves #7

Specify what GPU to use

---

lightwood/__about__.py
lightwood/api/data_source.py
lightwood/api/predictor.py
lightwood/config/config.py
lightwood/data_schemas/predictor_config.py
lightwood/encoders/numeric/numeric.py
lightwood/mixers/nn/helpers/transformer.py
lightwood/mixers/nn/nn.py
tests/ci_tests/full_test.py

Main feature:
* Allow for cache disabling via the `CONFIG`, this is useful for running large dataset, it does decrease speed but it doesn't seem to affect it that significantly. We should control this option dynamically from mindsdb in the future based on the computer's available memory and the dataset size (PR incoming tonight or tomorrow).
In the process of doing this I've removed the option to disable the cache for a particular column only, since it proved to cumbersome to implement properly and it was hardly working as intended. Might be worth looking at implementing it again when we have more time and/or when we restructure some of the dataset logic. But I don't think now is the correct moment.
Various fixes:
* Changed the r2 accuracy score for numerical target variables to use the …

Large data

---

lightwood/__about__.py
lightwood/api/data_source.py
lightwood/config/config.py
lightwood/mixers/helpers/default_net.py
lightwood/model_building/basic_ax_optimizer/basic_ax_optimizer.py
pr.ref.md
pr.ref.txt

Added random seeds wherever possible plus CUDA options to make training deterministic, in spite of what the pytroch docs say I haven't notice a significant decrease in lightwood training speed (< 1%)
Over 5x runs on default on credit and 2x runs on all the benchmark datasets (with optimization enabled) we got the exact same accuracy to the second to last decimal.
Also added explicit weight/bias initialization for the default net, so that doesn't change randomly when torch version gets changed or users have different versions of torch. Since already use the SELU activations I used the initialization they propose in their paper (see ` pr.ref.md `), for bias initialization I ended up using 0.1 (tried using `0` as their code shows but torch doesn't allow me to create a normal distribution …

Initialization seed

---

lightwood/__about__.py
lightwood/config/config.py
lightwood/mixers/helpers/default_net.py
lightwood/mixers/nn/nn.py

Selfaware was failing to train (loss started being nan after 2-4 batches) on all of our benchmark datasets and the testing dataset (home rentals). There seemed to be no obvious reasons for this, after further exploring it seemed to boil down to the awareness netwrok being to small to be train-able and/or the learning rate being too high (changing these fixed stuff on a case by case basis).
Thus the changes include:
* Increase awareness network size (4 layers, funnel shape)
* Decreasing Ranger's lr by 1/100 when selfware is toggled on 
Also:
* Cleaned up the selfaware code
* Added selfaware toggle via config
* Bumped version to re-deploy to pypi
Not, I haven't ran the benchmarks yet, running as we speak.

Selfaware fix

---

lightwood/__about__.py
lightwood/config/config.py
lightwood/encoders/categorical/__init__.py
lightwood/encoders/categorical/autoencoder.py
lightwood/encoders/categorical/categorical.py
lightwood/mixers/helpers/default_net.py
lightwood/mixers/helpers/shapes.py

Added a new **default** encoder for categorical data `CategoricalAutoEncoder`, and unit tests for this encoder.
The way it operates on a high level is as follows:
* Prepares a one-hot encoder for the column
* If the dictionary length (== nr of dimensions for the one-hot encoding) is smaller then what we set as `max_encoded_length` (set it to 100, but we could chose some other value), it operates just like a one-hot encoder. Otherwise, it train a very simple (input -> hidden -> SELU -> output) autoencoder and uses the `hidden` layer's output's in the `encode` method.
This does not seem to significantly affect any benchmarks, though it obtains worst values than the benchmarks done with `Oversample`, so I'd recommend merging #57 into `master` then merging `master` to this and running the …

Categorial autoencoder

---

lightwood/__about__.py
lightwood/api/data_source.py
lightwood/api/predictor.py
lightwood/encoders/__init__.py
lightwood/encoders/categorical/__init__.py
lightwood/encoders/categorical/autoencoder.py
lightwood/encoders/categorical/onehot.py
lightwood/encoders/image/img_2_vec.py
lightwood/encoders/image/nn.py
lightwood/encoders/numeric/numeric.py
lightwood/mixers/helpers/ranger.py
lightwood/mixers/nn/nn.py

Benchmarks are still running for this PR, I'll update it with the results when they are finished.
* If the losses get too large (inf or nan) we halve the learning rate and re-start training at that (resetting all the weights)
* If the overall error gets small enough (arbitrarily picked as `< 1`), then we switch the loss combination operator that combines the awarenessloss with the prediction loss is switched from 
* Extracting a confidence for the prediction from the awareness output and giving it to the user (this is computed at line 93 in nn.py), this is probably the most critical thing to review and possibly suggest changes to.
Basically, the categorical autoencoder wasn't playing along very well with a lot of the unbalanced-categories related features and with the CrossEntropy loss we …

Selfaware and autoencoding fixes

---

lightwood/__about__.py
lightwood/api/data_source.py
lightwood/encoders/text/__init__.py
lightwood/encoders/text/infersent.py
lightwood/mixers/helpers/default_net.py
lightwood/mixers/nn/nn.py

Lightwood now adds a parallel wrapper to the model when it detects a multi-GPU machine, this is done in such a way as to maintain the interface of the default net unchanged.
Made `InferSentEncoder` the default text encoder. This seems to help get some meaningful representation out of text (based on testing set accuracy) compared to the RNN encoder, but is very memory heavy and time consuming, we should probably review how it's implemented at a later stage.

Data parallelism

---

README.md
docs/docs/API.md
docs/docs/index.md
lightwood/__about__.py
lightwood/api/data_source.py
tests/ci_tests/full_test.py

* Updates the lightwood tests to cycle through a few options and try predicting both from the original dataframe and from a python3 dicitionary. Removed the second `learn` call, will add when we actually add some model-updating capabilities to lightwood. Currently it basically just re-trains the mixer.
* Made a few changes around handling missing columns when the cache is disabled so that it behaves the same way as when the cache is enabled
* @ZoranPandovski 's doc updates from https://github.com/mindsdb/lightwood/pull/85

Small fixes

---

lightwood/__about__.py
requirements.txt

This PR adds a specific botorch 0.1.4 version as a dependency since ax-platform will install the latest botorch version that doesn't work.

Fix dependency

---

lightwood/__about__.py
requirements.txt

Ax-platform has a new version release a few days ago that has fixed the issue with botorch. So, we don't need to install the specific botorch version.

Remove botorch from dependencies

---

lightwood/__about__.py
lightwood/api/data_source.py
lightwood/api/predictor.py
lightwood/config/config.py
lightwood/encoders/text/__init__.py
lightwood/encoders/text/tfidf.py
lightwood/mixers/boost/boost.py
lightwood/mixers/helpers/ranger.py
lightwood/mixers/nn/nn.py
requirements.txt
setup.py

* XDG scrapped in favour of sklearn since the mixers were buggy (failing to take sample weights into the account for no apparent reason... I tried my hardest to make them work), it also seems like their performance wasn't necessarily better and they weren't working on windows (sklearn works)
* Sourcing confidence from booster when they are used for predictions and only calling them for small datasets (since they are very fast, they are slower than the neural network on larger datasets... and decreasing the nr of estimator means their performance goes down the drain, especially on large datasets)
* Evaluating the model more often once dropout is enabled, decreased the learning rate and decreased the wramup period in order to diminish the problems discussed (models that fit the training set …

Learning rate and boosting bugs

---

lightwood/__about__.py
lightwood/encoders/categorical/autoencoder.py

This PR fixes missing logging error:
```
File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/lightwood/encoders/categorical/autoencoder.py", line 57, in prepare_encoder
logging.info('Preparing a categorical autoencoder, this might take a while')
NameError: name 'logging' is not defined
```

Fix missing logger error

---

lightwood/__about__.py
lightwood/config/config.py
lightwood/encoders/numeric/numeric.py

New simplified numeric encoding for targets.
Using a % error based accuracy score that's roughly this: `1 - abs((y_true - y_pred) / y_true)` (where y_true and y_pred are arrays and the operations are done element-wise).
On the home rentals dataset.
With helper mixers disabled (otherwise we get better accuracy with those and the neural network is ignored, the helper mixers predicted the un-encoded values so the encoding is not relevant there)
* master:  -1.4 pct accuracy score
* new encoding with the log representation (as per this PR): -0.5 pct accuracy score
* new encoding without the log representation: 0.6 pct accuracy score
* gradient boosting regressor: 0.95 pct accuracy score
Note 1 : with the ranged loss the last accuracy improves to ~0.8 I believe, which is close to the gradient …

New nr encoder

---

lightwood/__about__.py
lightwood/api/predictor.py
lightwood/config/config.py
lightwood/mixers/helpers/default_net.py
lightwood/mixers/nn/nn.py

* No longer passing the data source inside the `DefaultNet` since this was causing some issues (related to trying to deep copy the autoencoder which is part of the data source), instead just taking the entities we need (in this case the output indexes) from it.
* Re-enabled helper mixers (flag was turned off by mistake)
* Fixed a glaring error where running_loss was not updated in `iter_fit`

Fix covid crash

---

.travis.yml
lightwood/__about__.py
lightwood/mixers/nn/nn.py

See description of bug here: https://github.com/mindsdb/lightwood/pull/137
This basically handles the same issue as #137 but source `max_confidence` as the maximum overall confidence in the array, rather than the maximum out of those values smaller the 9th percentile.
Also, merged in here, removal of 3.6 and 3.8 travis tests envs to hopefully have more machine-power to allow travis tests on windows and osx to more easily pass (to be seen if this actually works).

Confidence bug fix

---

lightwood/__about__.py
lightwood/api/predictor.py
lightwood/config/config.py
lightwood/mixers/boost/boost.py

Added quantile prediction for the gradient booster in order for them to give use quantile intervals.
Quantiles are currently hardcoded in the config so that in the future we can use the same quantiles for the nn mixer.
Here's some results with the 0.95 and 0.05 quantiles:
```
Out of the intervals 251 were correct (real value was within the interval) and 63 were incorrect (real value was outside the interval)
Out of the intervals 314 contained only positive values and 0 contained at least one negative value (gross prediction error, since all the targets are positive)
The mean range of the intervals was 108.23336156530779
The standard deviation for the ranges was 161.41387342773075
```
Here's some results with the 0.85 and 0.15 quantiles:
```
Out of the intervals 197 were correct (real …
```

Gradient boosting quantiles

---

docs/examples/learn_to_multiply.py
lightwood/__about__.py
lightwood/api/predictor.py
lightwood/config/config.py
lightwood/encoders/numeric/numeric.py
lightwood/mixers/helpers/default_net.py
tests/ci_tests/ci_tests.py

* Changed the numerical encoder such that it encodes:
Ouputs: `[log(abs(real)) if abs(real) > 0 else -20  ,  1 if real < 0 else 0 , real/self._mean]` (i.e.: `[log, sign, normalized linear]`)
Inputs: `[is_not_null, log(abs(real)) if abs(real) > 0 else -20  ,  1 if real < 0 else 0 , real/self._mean]` (i.e.: `[is_not_null, log, sign, normalized linear]`)
* Added a decision in the `predictor.py` accuracy computation logic to switch to decoding the numeric target to either `log` or `linear` depending on which scores the highest accuracy on whatever score we use for numerical prediction evaluations (currently `r2_score`... though this *might* give an unfair advantage to linear encodings, @torrmal feel free to suggest a better score if you have one in mind, if not, I'll open an issue and we can …

New Numeric Encoder and decoding selection

---

lightwood/__about__.py
requirements.txt

This PR changes the transformers to be fixed to the 2.4.1 version, to avoid the issue reported with installing tokenizers ``ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot be installed directly``

Fix tokenizers error

---

lightwood/__about__.py
lightwood/api/data_source.py
lightwood/api/gym.py
lightwood/api/predictor.py
lightwood/encoders/categorical/autoencoder.py
lightwood/encoders/image/helpers/img_to_vec.py
lightwood/encoders/text/distilbert.py
lightwood/mixers/boost/boost.py
lightwood/mixers/helpers/quantile_loss.py
lightwood/mixers/nn/nn.py
tests/ci_tests/ci_tests.py

* Moved the training loop logic for the nn mixer into the `fit` function of said mixer (previously it was in `predictor.py`)
* Added dynamic adjustment on the quantile based on the average width of the interval between the two quantiles and the overall test dataset error (see `adjust_quantiles` and where it's called), probably not the perfect way to do it, but honestly, I tried a bunch of things and they all behave more or less the same, this one is relatively clean and easy to understand.
* Made sure `.eval()` and `torch.no_grad` are properly used in *all* the places where they should be.
* Added a few more parameters to the `.fit()` interface of both the NNMixer and the Gradient Boosting helper mixer. As it stands, I think most argument for `fit` should be optional, barring the …

Dynamic quantiles

---

lightwood/__about__.py
lightwood/api/predictor.py
lightwood/mixers/nn/nn.py

Solves #116  by only using 1 subset (so basically not using k-fold cross-validation) in the cases where the training data has <= 100 rows.
Granted, this number could be as low as 30 in theory, but in practice, I think we'd want our test sets to have > 1 example, we'll rarely have datasets this small anyway.
Fixed an issue where the quantile differences for choosing which quantiles to predict with were not computed as intended.

Few row fixes

---

lightwood/api/predictor.py
lightwood/mixers/nn/nn.py
scraps/bayesian_nn/bayesian_nn.py
scraps/mixer_with_gym_incomplete.py

Setting the quantile pair we are using based on the selfaware confidence.
We record the mean selfaware confidence for which a given quantile pair was correct (contained the real value) and compare the quantile confidence of a prediction with that mean.
We use the smallest quantile pair for which the associated selfaware confidence mean is bigger or equal to the selfaware confidence of the prediction. 
Removed the old quantile pair determination logic in favour of this one.

Quantile pair setting based on selfaware confidence

---

lightwood/__about__.py
lightwood/mixers/nn/nn.py

There was a minor bug that causes the (empty) arrays `confidence_range` and `quantile_confidences` to be created in the predictions for a non numeric target. Mindsdb isn't expecting this (it expects the arrays to always be full, which is always the case for numeric targets) and it caused crashes during the model analyses.

Hotfix to quantile arrays

---

lightwood/mixers/nn/nn.py
tests/ci_tests/ci_tests.py

* Fixed a bug with the way we transfered the output weights to the loss function where lightwood was trying to predict multiple categorical output
* Improved the CI test to try and predict numerical + categorical + categorical-weighted + categorical-weighted ... this should cover more weird edge cases around multiple-value predictions
* Added a quick fix in the mixer to stop training if the test loss is < 0.001

Multiple output categories fix

---

lightwood/helpers/text.py

Before that change:
`tokenize_text(['кириллица']) => []`
Now it should properly handle non-ascii alphanumeric strings.

Fix token filter so that unicode alphanumerics are also valid tokens

---

lightwood/encoders/numeric/numeric.py

this message used to spam the console a lot, I removed the "exception:" part in the error message and if-else is now used instead of try-except.
`ERROR:root:Can't encode target value: None, exception: '<' not supported between instances of 'NoneType' and 'int'`

fix None comparison

---

lightwood/encoders/encoder_base.py
lightwood/encoders/text/short.py
tests/unit_tests/encoders/text/test_short_text_encoder.py

related to https://github.com/mindsdb/lightwood/issues/218
- fix typo: `BaseEncoder.decoder()` in renamed to `BaseEncoder.decode()`
- `ShortTextEncoder` uses `"concat"` mode if `is_target is True` and tests for this are added too

use concat mode if is_target

---

docs/examples/home_rentals.py
lightwood/api/data_source.py
lightwood/encoders/datetime/datetime.py
lightwood/encoders/text/rnn.py
lightwood/encoders/time_series/cesium_ts.py
lightwood/encoders/time_series/rnn.py
lightwood/mixers/nn/nn.py
scraps/bayesian_nn/bayesian_nn.py
scraps/mixer_with_gym_incomplete.py

`list.__add__(a, b)` is `O(len(a) + len(b))`
`list.extend(a, b)` is `O(len(b))`
`list.append()` is `O(1)`
using `list.__add__` might slow down lightwood a lot, especially when there is a for loop like this:
```
ret = []
for x in L:
ret += [x]
```
because this is `O(n^2)`

use list.extend() and list.append() instead of list.__add__()

---

lightwood/mixers/nn/nn.py

* Made the optimizer args of the selfaware optimizer separate from those of the mixer optimizer
* Removed redundant cache-clearing logic when turning the selfaware on/off (was relevant before, but now no reallocation happens there so it's not too important)
* Added `max_epochs` arg to iter_fit and removed the `total_epochs` parameter from the mixer class. This change isn't *that* important but I need it for some future work and based on the way `iter_fit` evolved (basically became a private function) it makes no sense for that particular behavior to be set-able via a public property anyway + it was never used (As in, never modified).

Simplifications

---

lightwood/mixers/nn/nn.py

Review and merge #248 first.
Before finalizing training, run a single epoch on the testing dataset in order not to completely "waste" the information contained in it.
The validity of this approach is arguable (i.e. why not run 2 ? or 10 ? or 20 ?) but in practice it seems like it can do very little harm and has improved accuracy quite a lot on both "home_rentals" and "diamonds".

Single epoch on test

---

lightwood/mixers/nn/nn.py

Review and merge: #248 first
Remove logic around copying the best model that was linked to the selfaware network's status.
Since now the selfaware model is separate, it doesn't affect the logistics of copying so all that logic was redundant.
If we do want to copy the best selfaware network in the future, that will involve a separate confidence-accuracy evaluation step to determine which one is the best.

Removed selfaware-specific copying logic

---

lightwood/encoders/text/distilbert.py
tests/unit_tests/encoders/text/test_distilbert.py

Should fix [#671](https://github.com/mindsdb/mindsdb/issues/671)
- Removes `selfaware` argument passing in call to DefaultNet
- Restores DistilBert unit test to catch issues like this next time (for now, without asserting an accuracy threshold)

Hotfix for DistilBert call to DefaultNet

---

lightwood/encoders/time_series/helpers/rnn_helpers.py
lightwood/encoders/time_series/rnn.py

The RNN encoder transforms strings like `[1 2 3 4]` into `[1, 2, 3, 4]` sooner in the encoder and priming functions.
This also means it can be more easily removed once we make mindsdb_native only pass arrays to lightwood for timeseries columns.

Quicker ts-string to array transformation for the RNN encoder

---

lightwood/encoders/__init__.py
lightwood/encoders/time_series/__init__.py
optional_requirements.txt
requirements.txt
tests/unit_tests/encoders/time_series/test_cesium_ts.py
tests/unit_tests/encoders/time_series/test_ts_fresh_ts.py

Stop importing encoders that are no longer used, especially ones that require a special dependency.
Removed for now:
* cesium
* tsfresh

Stop importing old encoders

---

lightwood/data_schemas/predictor_config.py

Added and `additional_info` parameter to the feature_schema to allow for quickly prototpying working with new keys sent by native without have to release a new lightwood every time.

Additional info

---

lightwood/encoders/categorical/autoencoder.py
lightwood/encoders/datetime/datetime.py
lightwood/encoders/text/short.py
lightwood/encoders/time_series/rnn.py

- Added `is_target` to datetime encoder initializer
- Explicitly defined some functions that were lambdas and, as such, unpickable
- Handle edge case in categorical autoencoder
- Add RNN time series decoder to its `.to()` method (see #284), increased default hidden size

Some small fixes 

---

lightwood/api/data_source.py
lightwood/data_schemas/predictor_config.py
lightwood/encoders/time_series/helpers/rnn_helpers.py
lightwood/encoders/time_series/rnn.py

- Adds `CatNormalizer()` to one-hot encode categorical target column when fed into the RNN TS network.
- Improved / simplified logic in `setup_nn()` method

Categorical target support in time series

---

lightwood/helpers/device.py

Solves [this issue](https://github.com/mindsdb/mindsdb/issues/732).

Fix get_devices() using CUDA when it's not available

---

lightwood/api/predictor.py

logs what device is being used in `learn` and `predict` methods [here](https://github.com/mindsdb/lightwood/blob/stable/lightwood/api/predictor.py)

Fix for https://github.com/mindsdb/mindsdb/issues/798

---

lightwood/api/predictor.py

- Simple argument passing so that Native can ask for extra data. In particular, we need the score for each label in classification tasks (currently only NnMixer returns them, under the `encoded_predictions` key). These scores are used in the conformal predictor confidence estimation step.

include_extra_data on predictor call

---

lightwood/api/data_source.py

Addresses #306 
- Renames `previous_` columns to `__mdb_ts_previous_`, to avoid potential collisions with dataset's own columns.

Rename "previous_" columns 

---

setup.py

- Removed custom logic in `setup.py`, as error in #157 seems to not be happening anymore

Remove transformers==2.4.1 constraint for macOS

---

lightwood/encoders/datetime/datetime.py
tests/unit_tests/encoders/date/test_datetime.py

Addresses #235 and [N#92](https://github.com/mindsdb/mindsdb_native/issues/92).
- Determine monthly number of days given the year and month, instead of using a fixed value as before.
- Normalizes intermediate representation components in .decode() to avoid errors when NnMixer encodes values that are negative and/or too large.
- Introduces test for this.

DateTime encoder improvements

---

lightwood/api/data_source.py
lightwood/mixers/nn.py

The call to `DataSource.output_weights` in the `NnMixer` did not account for offsets in this array when some of the output features were non categorical, which meant an empty tensor was passed to the CrossEntropyLoss, resulting in this [issue](https://github.com/mindsdb/mindsdb_native/issues/291). This PR fixes the bug.

Offset for non-categorical features in DataSource.output_weights

---

lightwood/config/config.py
lightwood/mixers/helpers/default_net.py
lightwood/mixers/nn.py

- Adds dropout (`p = 0.3`) to the DefaultNet when used in the NnMixer, based on the results of our parameter search.
- Also simplifies logic in DefaultNet, deleting `deterministic` flag as most of that logic is already implemented in `__init__.py`

Dropout for DefaultNet

---

requirements.txt
setup.py

To keep Lightwood compatible with the latest version of PyTorch and Transformers.
Small caveat: PyTorch 1.7 will support Python 3.9 starting next version (1.7.1), which should be released this month.

Torch 1.7, Transformers 4.0

---

lightwood/encoders/numeric/numeric.py
tests/unit_tests/encoders/numeric/test_numeric.py

* When the log-representation of a number was too big for math.exp to work (e.g. 2000), it overflowed, this caused issues when the encoder was set to `decode_log=True` and the network generate values that were way too large for the log representation.
* When and overflow error is thrown by `math.exp` we instead assume that it returned a very large number and replace that number with `2^63`, same as we do for the "real" value when it's `inf`, then we go through the usual logic using this `2^63` value instead of the return value from `math.exp`
* Tests were added to check the numeric encoder in `decode_log=True` mode, this includes testing `.decode` with vectors like `[0,2^70,0]` which would cause an overflow for the `math.exp` function
Also added tests for encoding, decoding and priming …

Overflow fix for numeric decoding

---

requirements.txt

because numpy 1.19.4 has a bug on windows: https://github.com/twintproject/twint/issues/1030#issuecomment-726914912

requirements.txt: numpy != 1.19.4

---

lightwood/config/config.py

* `torch.cuda.device_count()` is bigger than 0 even if the devices are torch incompatible in some cases (@StpMax had this issue)
* Before setting GPU usage to True or False, try to create a GPU tensor consisting of one zero and set usage to False if this throws an exception.

Better cuda check

---

lightwood/api/gym.py
lightwood/encoders/audio/amplitude_ts.py
lightwood/encoders/categorical/multihot.py
lightwood/encoders/categorical/onehot.py
lightwood/encoders/datetime/datetime.py
lightwood/encoders/encoder_base.py
lightwood/encoders/image/helpers/img_to_vec.py
lightwood/encoders/image/helpers/nn.py
lightwood/encoders/image/img_2_vec.py
lightwood/encoders/numeric/numeric.py
lightwood/encoders/text/distilbert.py
lightwood/encoders/text/helpers/rnn_helpers.py
lightwood/encoders/text/rnn.py
lightwood/encoders/text/tfidf.py
lightwood/encoders/time_series/helpers/rnn_helpers.py
lightwood/encoders/time_series/helpers/transformer_helpers.py
lightwood/encoders/time_series/rnn.py
lightwood/encoders/time_series/transformer.py
lightwood/helpers/torch.py
lightwood/mixers/helpers/default_net.py
lightwood/mixers/helpers/plinear.py
lightwood/mixers/helpers/selfaware.py
lightwood/mixers/helpers/transform_corss_entropy_loss.py
lightwood/mixers/nn.py
scraps/bayesian_nn/bayesian_nn.py
scraps/mixer_with_gym_incomplete.py
tests/unit_tests/encoders/time_series/test_transformer.py

Automatic Mixed Precision (AMP) is a technique that enables using either full or half precision tensors at training time in a dynamic way, without compromising on accuracy while improving training runtime.
As of PyTorch 1.6, it's rather easy to enable AMP while following recommended guidelines. This PR adds an AMP context manager for forward and loss operations, based on Torch's original context manager. We use a custom manager to check the device computing capability: if the GPU has no tensor cores, then enabling AMP yields a slower runtime. 
Another change is that now we cast the output to a generic tensor instead of a specific wrapper per each encoder, because doing so triggers errors given the dynamic change in type that can happen while using AMP.
Finally, there are some changes in …

Automatic mixed precision

---

lightwood/api/data_source.py
lightwood/mixers/helpers/ranger.py
lightwood/mixers/nn.py

During training, Lightwood raises some warnings that are mostly due to outdated function call signatures in the ranger optimizer and NnMixer.
This PR updates those calls, which results in fewer raised warnings.

Update calls to avoid warnings

---

lightwood/mixers/base_mixer.py
lightwood/mixers/nn.py

See #347 for more error details. The situation is that whenever a time series predictor is trained for a binary/boolean categorical target with `nr_predictions > 1`, the temporally displaced target columns insert '0' values, which are foreign to the previously built `weight_map`, thus raising the KeyError when trying to access `weight_map['0']`.
The fix is to set any unrecognized class with a null weight, avoiding the error without affecting the accuracy estimation. 
Also, a handler is added for the case when Native passes a test dataframe with less rows per `group_by` than the specified `nr_predictions` (see [N#374](https://github.com/mindsdb/mindsdb_native/issues/374)), returning `NaN` in this case.

Fix for #347 - set invalid keys to 0 in class weight_map

---

lightwood/api/data_source.py
lightwood/encoders/categorical/autoencoder.py
lightwood/encoders/categorical/onehot.py
lightwood/mixers/boost.py
lightwood/mixers/nn.py
lightwood/mixers/sklearn_mixer.py

For classification tasks, we need Lightwood to return the complete class distribution probabilities for certain scenarios downstream, like using XAI techniques like LIME, or running MindsDB in the OpenML AutoML benchmark suite.
Added support for returning class probabilities in all mixers (SkLearn and Boost by calling `.predict_proba(X)`, NnMixer by adding non-calibrated softmax to the one-hot encoder). Predictions are now sent to native as a dictionary.

Class distribution for classification tasks 

---

lightwood/encoders/time_series/rnn.py

There were some outdated calls to the time series normalizers, which resulted in runtime errors.
Updating the calls to the correct methods.

Fix TS normalizer decoder call

---

lightwood/config/config.py

PyTorch reports CUDA availability even when the pre-built wheel might contain instructions that are not supported by older GPUs (compute capability must be `>= 3.7`, otherwise PyTorch should be built from source). This should be considered in the logic that determines CUDA usage.
By checking `torch.cuda.get_device_capability() >= 3.7` when setting the `USE_CUDA` flag.

add compute capability >= 3.7 check

---

lightwood/api/data_source.py
lightwood/encoders/encoder_base.py
lightwood/encoders/time_series/rnn.py

The `historical_columns` feature was failing, see [N#398](https://github.com/mindsdb/mindsdb_native/issues/398) for more details.
Add `original_type` handling inside time series encoders common loop to normalize the input based on its value.
Also, removed an unnecessary `.to(device)` cast inside `_prepare_raw_data()`.

Small time series fixes

---

lightwood/__about__.py
lightwood/config/config.py

See related issue [here](https://github.com/mindsdb/mindsdb_native/issues/407).
Basically, there were some edge cases where GPU detection was failing. For example, using a torch wheel without GPU support in a system with a GPU, and then training a model in Native with `use_gpu=False`.
The cause is somewhat weird. Apparently, `torch.ones(1).cuda()` can be lazy in some scenarios, thus not triggering a RuntimeError and incorrectly setting `USE_CUDA=True` in `lightwood.config.config`. A fix is to force the error by calling `.__repr__()` in that instruction, which is what this PR does.

Improved gpu detection, fixes n#407

---

lightwood/mixers/sklearn_mixer.py

Confidence estimation was failing in Native if the SkLearn mixer chose to use `GaussianNB`, because this class does not have a `decision_function` method.
Simple PR that checks the type of chosen model. If we use GaussianNB, then call `predict_proba()` instead of `decision_function()`.

Fix sklearn GaussianNB

---

lightwood/mixers/lightgbm.py

LightGBM mixer had inconsistent behavior compared to other mixers: its 'class_labels' output was a list instead of a dictionary.
Very simple change to conform with the expected format.

Fix: LightGBM class_labels -> dictionary

---

lightwood/mixers/lightgbm.py

Edge cases with very little training time would trigger a call to LightGBM with no iterations, raising an exception.
Adding a safeguard to execute at least one iteration.

Fix: LightGBM mixer minimum iterations

---

lightwood/mixers/helpers/default_net.py

As framed in #378, there were certain cases for which the concatenated input tensor to the DefaultNet was very big, and this led to prohibitively big NnMixers. 
As an example, let's consider the `micro_mass` [dataset](https://www.openml.org/d/1514), which has some 1.3k columns. After all respective encoders have been trained, the NnMixer has to deal with (or learn from) a `(B, 6072)` shaped input tensor. The current shape policy for the NnMixer's DefaultNet would then instantiate a sequential model with dimensions `[6072, 12144, 3]` with some 220 million trainable parameters. This, naturally, led to incredibly long training times with poor performance to boot. 
The PR introduces a non-destructive additional size check, where we check if the candidate shape for the NnMixer has less than …

Improved DefaultNet shape policy

---

lightwood/helpers/torch.py
lightwood/mixers/nn.py

With Automated Mixed Precision, sometimes gradients would underflow, resulting in NaNs being propagated.
Implementing `torch.amp.GradScaler` recommended usage.

Add GradScaler for AMP usage

---

lightwood/encoders/time_series/rnn.py

A dumb mistake in a batching method meant increasingly larger batches when training the TS RNN encoder. Given a sufficiently large dataset, it meant the GPU went out of memory quite easily.
Fixing the logic inside the method.

Fix TS RNN batching

---

lightwood/__about__.py
lightwood/api/data_source.py

Text encoder was triggering an IndexError, this PR solves that.
Reordering the `prepare()` call to lightwood encoders, so that now we:
1. Add information to "autoregressive" time series columns
2. Train all output column encoders except for time series ones (as they require input columns' encoded data)
3. Train all input column encoders
4. Train all time series output column encoders
This restores the information flow that was lost in the #382 rearrangement, and fixes #393.

Hotfix: prepare_encoder order call

---

tests/unit_tests/test_predictor.py

With regards to: [Issue 393](https://github.com/mindsdb/lightwood/issues/393)
The recent change to data_source.py influences the text encoder. This simple additional test checks to see if the text encoder is properly called by ensuring the config file tells lightwood that the input column is a text-type.
You can check this behavior between stable (0.60.0) and fix_l393
git checkout stable
python -m unittest test_predictor.TestPredictor.test_text_encoder
Versus
git checkout fix_l393
python -m unittest test_predictor.TestPredictor.test_text_encoder
The fix_l393 should be merged into stable in addition.

Unittest text

---

lightwood/api/data_source.py

Fixes #341 
Adding info of dependent columns when building the `custom_data` dictionary.

Fix dependent column info passing in custom_data 

---

lightwood/encoders/categorical/autoencoder.py
lightwood/encoders/encoder_base.py
lightwood/encoders/image/helpers/img_to_vec.py
lightwood/encoders/image/helpers/nn.py
lightwood/encoders/image/img_2_vec.py
lightwood/encoders/text/distilbert.py
lightwood/encoders/time_series/rnn.py

To minimize risk of model transfer issues. For more context, see #282.
Modified `BaseEncoder.to()` so that it sends all `torch.nn.Module()` atributes to the respective device. This simplifies `.to()` logic in a bunch of encoders.

Improved BaseEncoder .to()

---

lightwood/encoders/numeric/__init__.py
lightwood/mixers/lightgbm.py
tests/unit_tests/encoders/numeric/test_numeric.py
tests/unit_tests/mixers/test_ligthgbm.py

As the LightGBM mixer does not use any encoder `.decode()` methods, our `positive_domain` logic for the NnMixer was not being used, and so negative predictions would arise even if the user specified this flag.
Added a check in the `._predict()` method.
Also, added `TsNumericEncoder` to `test_positive_domain`.

Positive domain handling for LightBGM mixer

---

.github/workflows/ligthtwood.yml
lightwood/__about__.py
lightwood/encoders/time_series/rnn.py
requirements.txt

Hotfix:
- Bounds PyTorch to `>= 1.6.0` as needed by the `torch.cuda.amp` module.
- Implements empty order by column handling in time series encoder (solves #407)

hotfix: torch >= 1.6

---

lightwood/mixers/lightgbm.py

Solves #404 
- fix bug in `seconds_for_one_iteration` definition
- add `time_budget` keyword argument for Optuna LightGBMTuner, forcing at most `stop_training_after_seconds` seconds of grid search

Improved time budgeting for LightGBM mixer grid search

---

.github/workflows/ligthtwood.yml
lightwood/mixers/helpers/selfaware.py
lightwood/mixers/nn.py

The SelfAware NN job has changed slightly since it was implemented: the scores it sends to Native now should represent a "sample difficulty" estimation rather than a confidence, because that part is now handled by the ICPs in Native.
This PR:
- Makes the SelfAware NN smaller
- Modifies its forward pass to only use the NnMixer input vector
- Stores mean reference "base loss" observed after training
- Changes the scores themselves to the formula: `1+(abs(selfaware(x))/reference_loss)`

Smaller Self-Aware

---

lightwood/api/ensemble.py

To continuously train predictors from streams of data.
Added a `LightwoodEnsemble` class that holds and uses an array of `Predictor`s to operate.
As this is a proof of concept, predictions for now are extremely simple: mode is taken for classification targets, and mean for regression targets.

LightwoodEnsemble

---

lightwood/ensemble/best_of.py
lightwood/helpers/general.py

All accuracy functions are expected to be bounded between 0 and 1. Current method (mean absolute error) does not comply.
Change to mean R2 score (averaged over all forecast horizon timesteps).

Bounded array accuracy function

---

lightwood/api/json_ai.py
lightwood/api/types.py
lightwood/data/statistical_analysis.py
lightwood/encoder/numeric/numeric.py
lightwood/encoder/numeric/ts_array_numeric.py
lightwood/encoder/numeric/ts_numeric.py
lightwood/model/lightgbm.py

To reintroduce flagging a target as having positive domain (see #460).
Logic was in place for the most part, but the actual check was missing from the statistical analysis + JSON AI dispatch.

Reintroduce positive domain target

---

lightwood/analysis/model_analyzer.py
lightwood/api/json_ai.py
lightwood/data/cleaner.py
lightwood/data/statistical_analysis.py
lightwood/data/timeseries_transform.py
lightwood/encoder/categorical/autoencoder.py
lightwood/encoder/time_series/rnn.py
lightwood/helpers/general.py
tests/integration/advanced/test_timeseries.py

Fixes:
- #459
- #462
For #459:
- Add respective parameters to `TimeSeriesEncoder` and `CategoricalAutoEncoder` signatures
For #462:
- Use `ArNet` in the Neural model only if `use_previous_target = True`
- Add `SkTime` to predictor models only if `use_previous_target = True`
- Decouple addition of future target values from previous target values in `timeseries_transform`
- Revert to not dropping the target column in predict mode if anomaly detection mode is active
- Expanded integration test to cover `anomaly_detection` on and off _and_ `use_previous_target` on vs off
- When needed, target type casting to `float` in analysis and array accuracy helper

Fixes -- #459 #462

---

lightwood/data/cleaner.py

Casting integers and floats to their respective types in the cleaner now takes into account `None` values and leaves them as is (since the respective encoders handle `None`).
In addition: Int/float cleaning in the cleaner now also converts nan-stlye values (nan, inf ,etc) into `None`.

Casting fix

---

lightwood/analysis/nc/nc.py

Analysis is currently saving a copy of the model inside each group confidence model. This means for tasks with multiple time series, memory usage is much larger than needed.
Custom `__deepcopy__()` method for `BaseModelNc` does not copy the model when doing `deepcopy(icp)` during analysis.
* `lightwood.analysis.nc`

Fix analysis memory usage

---

lightwood/encoder/numeric/ts_numeric.py
lightwood/helpers/ts.py
lightwood/model/neural.py

Fixes #461, #488 and #495
- #461: remove warmup step in `fit()` training loop _and_ modify policy for deciding to early stop by giving more importance to most recently seen errors, to avoid premature early stopping.
- #488: cast unitary forecasts from list to first (and only) value to keep original column format
- #495: add special handling for groups where `mean = 0.0`
- `lightwood/model/neural`
- `lightwood/helpers/ts`
- `lightwood/encoder/numeric/ts_numeric`
Reverting back to no warmup in neural model means that it is once again able to produce sane forecasts. Here is an example (monthly sunspots test split):
Before:
After:
As reference, new R2 score in one-step-ahead forecasts for the test set is `0.803`. Before, it was `-1.105`. Comparisons against `lightwood <= 0.69.0` + …

Fix 461, 488, 495

---

lightwood/api/json_ai.py
lightwood/api/types.py
lightwood/data/infer_types.py
lightwood/data/statistical_analysis.py
lightwood/helpers/seed.py

Batch improvements based on suggestions from @hakunanatasha after her extensive review of the codebase.
* Seed function no longer has a default value for the seed, the seed_nr being passed is configurable from all of the functions that `seed` is called in.

Seed keyword passed

---

lightwood/api/json_ai.py
lightwood/helpers/templating.py
tests/integration/basic/test_boston_housing.py

The title is self-explanatory, also added tests to check if lightwood handles names with `'`, `"`, `{` and `}` properly.
Closes #464

Handle ' and " in column names

---

lightwood/data/cleaner.py
lightwood/data/statistical_analysis.py
lightwood/helpers/numeric.py
tests/integration/basic/test_analyze_dataset.py

We weren't generating histograms for DateTime and tag types, our histograms for dates were arguably bad (using categorical histogram).
Added  a numeric-like histogram for dates, using categorical histogram for tags
Resolves #479  | Obviously histograms can still be improved but this is the  bare minimum to get some decent graphics in the GUI in the vast majority of cases.

Enhanced date-time + tag histograms

---

lightwood/analysis/explain.py
lightwood/analysis/nc/icp.py
lightwood/analysis/nc/nc.py
lightwood/analysis/nc/wrappers.py

We need to make lightwood's inferences faster. Non conformist is very slow, `explain` takes 40-90% of inference time, see these tests for detail: https://github.com/mindsdb/magazine_of_magical_minutia/blob/master/performance_benchmarks/Results_Lightwood.md
Optimizations to `explain increase performance across the board.
Example on bench 3
Before:
```
3.376 <module>  lightwood_benchmark_3.py:1
`- 3.367 predict  ../../../tmp/4f35588c6bb1fff0ac002432f937e88e2054d0e88762253d16309827790861123.py:162
|- 2.931 explain  lightwood/analysis/explain.py:14
```
After:
```
1.747 <module>  lightwood_benchmark_3.py:1
`- 1.733 predict  ../../../tmp/5f283d544a1c1c511a03088822d4e48f62b680f06ec161f816311097846519938.py:162
|- 1.398 explain  lightwood/analysis/explain.py:13
```
Example on bench 1
Before:
``` …
```

Nonconformist optimizations (for speed)

---

lightwood/model/sktime.py
requirements.txt

To fix #510 -- a warning that pops up while installing lightwood dependencies
Remove `[arima]` from `sktime` dependency, as `pmdarima` is enough.
Unrelated, but this PR also supresses warnings from `statsmethods` in the `AutoARIMA` model, as the user cannot act upon them and they are not very informative.
- `requirements.txt`

Fix #510 - Sktime dependency

---

lightwood/mixer/lightgbm.py

LightGBM's function to check GPU support (`check_gpu_support`) only checked if lgbm was installed with GPU enabled.
*But* the way we use LGBM means we also need torch installed with GPU support, so lightwood was failing in the odd case where the user had and lgbm install with GPU support but no torch with cuda support.

Fix for lightgbm device check

---

lightwood/api/json_ai.py
lightwood/data/cleaner.py
lightwood/data/statistical_analysis.py
lightwood/encoder/categorical/autoencoder.py
lightwood/encoder/categorical/gym.py
lightwood/encoder/text/short.py
tests/unit_tests/encoder/text/test_short.py

Categorical AE and implicitly Short text encoder no longer switch to OHE mode for < 100 categories
Fixed bugs where pandas is replacing `None` with various stuff that's something else by aggressively checking all values pandas might replace `None` with and converting them back to `None` at cleaning time.
Addresses #547

Select OHE at json-ai build time and fix pandas None bugs

---

lightwood/api/json_ai.py
lightwood/ensemble/best_of.py

* Unstable mixers can fail without the `predict` method throwing when `BestOf` ensemble is used
* If columns are missing in the `predict` data frame we replace them with an array of `None`
* Made json ai custom modules / editing work when lightwood is launched  as a mindsdb subprocess

Various fixes based on mindsdb CI

---

lightwood/encoder/array/array.py
lightwood/encoder/datetime/datetime.py
lightwood/encoder/helpers.py
lightwood/encoder/time_series/helpers/common.py
lightwood/encoder/time_series/rnn.py
tests/unit_tests/encoder/time_series/test_timeseries_rnn.py

To streamline the codebase.
As these normalizers are no longer TS-only blocks, so it makes sense to move them to `lightwood/encoders/helpers`.
Additionally, added/modified docstrings of:
- `ArrayEncoder`
- `DatetimeEncoder`
- `TimeSeriesEncoder`

Move array/TS normalizers to generic helpers

---

docssrc/source/analysis.rst
docssrc/source/api.rst
docssrc/source/data.rst
docssrc/source/data/cleaner.rst
docssrc/source/encoder.rst
docssrc/source/ensemble.rst
docssrc/source/helpers.rst
docssrc/source/index.rst
docssrc/source/mixer.rst

We need to migrate to the latest sphinx to use something like autosummary in order to not document like we're in the stone age.
*But* until we can do that we need to at least display most of what's documented in the actual docs.
This adds the doctree for the `__init__.py` file of each top-level lightwood directory to the index.
It also removes some extra headings which caused really nasty hierarchies with 1 to 3 elements that had a single child.

Documentation for /most/ lightwood modules

---

lightwood/api/json_ai.py
lightwood/api/types.py
lightwood/encoder/__init__.py
lightwood/encoder/type_encoder_maps/Array.py
lightwood/encoder/type_encoder_maps/Audio.py
lightwood/encoder/type_encoder_maps/Binary.py
lightwood/encoder/type_encoder_maps/Categorical.py
lightwood/encoder/type_encoder_maps/Date.py
lightwood/encoder/type_encoder_maps/Datetime.py
lightwood/encoder/type_encoder_maps/Float.py
lightwood/encoder/type_encoder_maps/Image.py
lightwood/encoder/type_encoder_maps/Integer.py
lightwood/encoder/type_encoder_maps/Quantity.py
lightwood/encoder/type_encoder_maps/Rich_Text.py
lightwood/encoder/type_encoder_maps/Short_Text.py
lightwood/encoder/type_encoder_maps/Tags.py
lightwood/encoder/type_encoder_maps/TimeSeries.py

- Json ai now *requires* explicit `data_type`s for all the features instead of sourcing them from the namespace of the encoder
- Removed "typed" encoder namespaces and their usage

Remove type mapping

---

lightwood/data/timeseries_transform.py

See title. This can happen when group by columns have e.g. integer values, so the following line will fail:
```python
df_gb_map['_' + '_'.join(gb)] = df
```
Type cast to string all group by values before populating the map.

Fix: cast TS group by values to string to avoid TypeError

---

lightwood/helpers/text.py

Dropping columns that don't have any information (a single unique value) 
Currently no test for this since `get_identifier_description` has no tests (maybe todo for later) and this is so dumb it's not the first thing I'd want to test, see #735

Drop column with no information

---

lightwood/api/json_ai.py
lightwood/api/predictor.py

For a simplified signature in `predictor.adjust()`. "Fixes" #719. 
Nothing weird going on. Simple modifications to `JsonAI` and `PredictorInterface`.

Streamlined predictor.adjust signature

---

lightwood/api/json_ai.py
lightwood/data/cleaner.py
lightwood/mixer/sktime.py

See #756 for more details.
Adding `tss.group_by` columns to list of exceptions that should not be dropped.
Unrelated, this fixes sktime mixer's behavior so that it outputs a single number (instead of a list wrapping around it) if `nr_predictions == 1`.

Do not drop single-group-by column (fix #756)

---

lightwood/__about__.py
lightwood/api/json_ai.py
lightwood/api/types.py
lightwood/data/statistical_analysis.py
lightwood/encoder/categorical/binary.py
lightwood/encoder/categorical/onehot.py
lightwood/ensemble/best_of.py

What's the bug here?
The One hot encoder and the binary were **inverting** the target weights argument when creating the weights-per-index tensor (used by the Neural mixer).
Why was this not affecting accuracy?
- Because we never weighted manually, only automatically, and instead of passing the *reverse* occurrence of every class to the encoders we were passing the occurrence of every class ... so double investing => all is good
This fix means that the `target_weight` argument now works with the `Neural` encoder *and* might increase accuracy in the case where implicit weights were passed to LightGBM, since the latest release it takes weight into account.
I'm actually surprised we didn't see more of an accuracy drop due to passing the wrong weights to LGBM in the previous PR, but I guess …

OH and Binary Encoders weighting fix

---

docssrc/source/_templates/layout.html

This PR adds two GTM scripts to the default layout so they will be injected in all autogenerated pages.

Extend default layout to include GTM scripts

---

lightwood/encoder/image/helpers/img_to_vec.py
lightwood/encoder/image/img_2_vec.py

Fixes minor issue where if torchvision is not installed, will print a log message and enable execution; allows lightwood to be imported if no torchvision is found.

fix: fixes missing torchvision import

---

lightwood/encoder/image/helpers/img_to_vec.py
lightwood/encoder/image/img_2_vec.py

Torchvision (and PIL) is required for image encoding but is an optional dependency for lightwood altogether; we opt to remove it from default installation as image-encoding is not a generic task. 
Since it was removed from the default requirements, users without torchvision can run into issues nstalling lightwood due to a failed import in the img encoder; this PR includes a simple try-exception around the imports and outputs a log that suggests these encoders cannot be used if the user does not install torchvision, and PIL

fix: try-catches import of img encoder to bypass module issue

---

lightwood/helpers/accuracy.py

Added the aforementioned scores, they require some assertions for their usage to make sense *and* they require `int` conversion for sklearn interface compatibility.
In theory, we could have a more generic recall_for_{label} score, but for now, we are sticking with the "standard" that defines true/1 as "positive" and false/0 as negative.

Precision recall and f1

---

lightwood/analysis/analyze.py
lightwood/api/json_ai.py
lightwood/api/types.py
tests/integration/basic/test_categorical.py

To enable lean predictors that do not run an analysis phase at all.
Added an argument in the problem definition to explicitly ask for _no_ analysis blocks to be deployed. Also, fixed a missing default value for the `cm` key in the runtime analyzer.

Fix no analysis blocks option

---

lightwood/data/timeseries_analyzer.py
lightwood/data/timeseries_transform.py
tests/integration/advanced/test_timeseries.py

To avoid incorrect temporal delta estimation of 0.0, which means any forecasts will be made for the same timestamp.
- Drop any duplicate timestamp from the sorted dataframe (this way, `0.0` is never a contender for most popular distance)
- Sort the DF in `timeseries_transform` even if non-grouped (this was missing and implicitly assumed up until now)
- Modify one of the tests to check this is solved

Fix: temporal delta estimation for ungrouped series

---

lightwood/analysis/explain.py
lightwood/data/cleaner.py
lightwood/data/statistical_analysis.py
tests/integration/advanced/test_timeseries.py

MindsDB needs this information to join predictions back with original queries. Lightwood, on the other hand, offers no guarantee regarding output order for timeseries use cases because it prioritizes sorting by the `order_by` columns.
This PR adds an extra column that will let MindsDB align predictions back to whatever the original row order of the query was.
Add an index column to the DF at the start of the cleaning process. It is not used in the rest of the pipeline, but stays there and is added to the output DF in the base explainer.
Also, add a check in one of the time series tests to ensure this column is added to the output.

Add original query index column in output

---

lightwood/analysis/nc/base.py
lightwood/analysis/nc/calibrate.py
lightwood/analysis/nc/icp.py
lightwood/analysis/nc/nc.py
lightwood/analysis/nc/util.py
lightwood/api/types.py

To improve inductive conformal prediction runtime (both calibration and inference).
Quite a few changes:
- `CachedClassifierAdapter` now returns raw probabilities to the ICP
- `BaseICP` now has a `validation_size` parameter (and the associated method `_reduce_scores()`) to keep the amount of reference nonconformity scores under the specified threshold. For now (and unless requested in the future and/or suggested by the pending confidence benchmarks), we are setting this value to 100. This improves the runtime.
- Removed inefficient procedure that would check classifier confidence more times than necessary. This alone yields 20x improvement in compute savings. Now the call is done once, and we retrieve the raw  p-values to build the final confidence estimate.
- Modified computation of …

Optimized classifier ICP block for confidence estimation

---

lightwood/api/json_ai.py
lightwood/helpers/log.py

To communicate runtime of a predictor while training, predicting, etc. to a user.
Added a decorator that is used in all `PredictorInterface` methods and will 1) log the runtime of each method at the `DEBUG` level and 2) store the runtime in the `runtime_log` field.

Compute & log time per phase

---

lightwood/mixer/regression.py

In some cases regression coefficients get really big (like 10^7 kinda big) and you get overflow from small variations in parameters. Using Ridge regression fixed this in the one case where we detected a glaring error.

Use Ridge Regression

---

lightwood/api/json_ai.py

Simply moves the `mixer.fit` call into a `Predictor` method so that we can decorate it with `timed`.

fix: add runtime per mixer

---

.github/workflows/ligthtwood.yml
tests/unit_tests/encoder/text/test_pretrained.py

- Fix some leftover credential passing in the github actions workflow
- Remove torch==1.7.0 requirement for windows
- Ignore Windows+Python3.9 tests for now, due to a dependency issue where sktime does not offer a precompiled wheel.

Restore Windows CI

---

README.md

I followed the instructions for [setting up a dev environment](https://github.com/mindsdb/lightwood#setting-up-a-dev-environment) and found that the installation of `requirements_image.txt` was missing (otherwise, the line `python -m unittest discover tests` fails).

fix: add complete instructions for setting up a dev environment

---

docssrc/source/tutorials/custom_cleaner/custom_cleaner.ipynb
lightwood/api/json_ai.py
lightwood/data/cleaner.py
lightwood/data/infer_types.py
lightwood/helpers/imputers.py
lightwood/helpers/text.py

To improve upon the previous fix (#866).
- Drop strict termination if high amount of missing values are present in a column, plus better type inference if said column is numerical.
- Fix float cleaning function to cover "." edge case.
- Add target imputers by default in JsonAI for TS predictors.

Fix 863 v2

---

lightwood/analysis/nc/calibrate.py
lightwood/data/timeseries_analyzer.py
lightwood/encoder/numeric/ts_numeric.py
lightwood/encoder/time_series/helpers/common.py
lightwood/encoder/time_series/rnn.py
lightwood/helpers/ts.py
lightwood/mixer/sktime.py

Fixes:
- Will choose most popular _non-null_ delta for each series
- Changes `frozenset` to `tuple` to avoid ordering issues and potentially missing out on training data

Fix: non-null TS delta analysis

---

lightwood/data/cleaner.py

Fixes #877. Simply imputes `0` if the cleaned string (without quantity symbols) has no content at all.

Fix #877 - Improved quantity cleaner

---

lightwood/data/cleaner.py
lightwood/data/timeseries_transform.py
tests/integration/advanced/test_timeseries.py

To enable greater control of row selection to generate forecasts from MindsDB, enabling efficient usage of syntax like `WHERE T = LATEST`
Add special column `__mdb_forecast_offset` that can be either None or an integer. If this column is passed, then the TS transformation will react to the values within:
* If all rows have it set to `None`, then we proceed as usual
* If all rows have the same value `N <= 0`, then we cutoff the dataframe latest `-N` rows after TS shaping and prime the DF (via `__make_predictions` column) so that a forecast is generated only for the last row. This enables `WHERE T = LATEST - K` with `0 <= K < WINDOW` syntax, though realistically any `K != 0` will probably not be useful.
* If all rows have the same value `N = 1`, then we activate streaming inference mode …

Offset handling for TS predictions

---

lightwood/encoder/helpers.py
lightwood/encoder/time_series/ts.py
lightwood/mixer/lightgbm.py
lightwood/mixer/lightgbm_array.py
requirements.txt

To achieve better trend modelling (for when test data is outside of the previously seen range) in the `LightGBMArray` mixer.
Forces `linear_tree` param to be true.

Linear tree for LightGBM array mixer

---

lightwood/analysis/nc/calibrate.py
lightwood/helpers/__init__.py
lightwood/helpers/ts.py

To improve support for categorical forecasters.
Adds a baseline method to extend the confidence level across the entire horizon so that the output type is consistent with the numerical target case.

[ENH] Add tn_conf for categorical targets

---

lightwood/analysis/explain.py
lightwood/analysis/helpers/feature_importance.py
lightwood/analysis/nc/calibrate.py
lightwood/api/json_ai.py
lightwood/api/types.py
lightwood/data/cleaner.py
lightwood/data/timeseries_transform.py
lightwood/helpers/ts.py
lightwood/mixer/lightgbm_array.py
lightwood/mixer/nhits.py
lightwood/mixer/sktime.py
tests/integration/advanced/test_timeseries.py
tests/integration/basic/test_model_selection.py

Support for multiple order-by columns is not the most robust feature, and hasn't really seen usage, so this PR drops it to simplify the codebase.
Refactored wherever it was necessary.

[MAINT] `order_by` is now a single column

---

lightwood/analysis/explain.py
lightwood/helpers/ts.py

To follow best Pandas usage practices.
Slight reformatting to avoid `SettingWithCopyWarning`s within TS-specific methods.

[FIX] Pandas copy warnings in TS logic

---

lightwood/data/statistical_analysis.py

`StatisticalAnalysis` can be used within MindsDB for data visualization purposes. Short, descriptive messages should accompany all relevant insights, `missing` among them. We currently don't do that, which is what the PR fixes. 
Added a short descriptive message.

[ENH] Message for missing values

---

lightwood/api/json_ai.py
lightwood/data/timeseries_analyzer.py
lightwood/data/timeseries_transform.py
lightwood/helpers/ts.py
lightwood/mixer/__init__.py
lightwood/mixer/arima.py
lightwood/mixer/ets.py
lightwood/mixer/sktime.py
requirements.txt
tests/integration/basic/test_model_selection.py
tests/unit_tests/data/test_transform_ts.py
tests/utils/timing.py

To offer a broader set of forecasting mixers, and to leverage the `BestOf` model selection phase as default behavior.
- Subclass `sktime` mixer for new classes that specifically use `AutoETS` and `AutoARIMA`, respectively. Both are added to the default set of mixers in forecasting tasks.
- `sktime` now by default tries `Croston`, `STL`, `Theta`, `Polynomial` and `Naive` internally. Any of these may be made a new mixer in the future by following in the steps taken in the aforementioned new mixers.
- Changed naive residuals to account for "true" T+N tasks (currently does T+1, and so has an unfair advantage compared to the actual mixers). This should provide a better indication of the mixer performance with unseen data.
- Added check for malformed partitions that, given some set of group-by …

[ENH] New defaults for sktime mixer, new AutoETS and AutoARIMA mixers

---

lightwood/analysis/helpers/acc_stats.py
lightwood/api/json_ai.py
lightwood/helpers/__init__.py
lightwood/helpers/general.py

To improve interpretability of reported accuracy for forecasting predictors.
Change default accuracy function in forecasting use cases to `bounded_ts_accuracy`.

[ENH] Enforce bounded_ts_accuracy as default

---

lightwood/analysis/helpers/feature_importance.py
lightwood/analysis/nc/calibrate.py
lightwood/analysis/nn_conf/temp_scale.py
lightwood/api/json_ai.py
lightwood/helpers/templating.py
tests/integration/advanced/test_custom_modules.py
tests/integration/basic/test_categorical.py
tests/integration/basic/test_jsonai.py

For a simpler, better, streamlined UX with analysis blocks.
- Added a topological sorting procedure to determine valid execution order in case that inputs are incorrectly ordered.
- Improved missing params insertion for default blocks
- Minor modifications to some blocks, in particular `GlobalFeatureImportance` normalization is now based on the obtained accuracy rather than passing through a low-temp softmax.
In practice, this implies a substantial change in the amount of boilerplate needed to specify an analysis chain.
From:
```python
[...]
jai = json_ai_from_problem(df, pdef)
jai.analysis_blocks = [
{
"module": "ICP",
"args": {
"fixed_significance": None,
"confidence_normalizer": False,
"positive_domain": "$statistical_analysis.positive_domain",
},
},
{
"module": "AccStats",
"args": …
```

Improved JsonAI templating for analysis blocks

---

lightwood/data/timeseries_transform.py

For improved performance on time series, particularly for long horizons and/or windows. Fixes #893.
Rewrote two core methods in the `timeseries_transform` to follow pandas best practices.

[ENH] Improved TS reshaping

---

lightwood/mixer/lightgbm_array.py

To fix #967 
Essentially all this does is activate `optuna` only if `tss.horizon < 10`.

Fix: faster LightGBM Array mixer

---

lightwood/data/infer_types.py
lightwood/helpers/text.py
requirements.txt
tests/unit_tests/data/test_infer_types.py

Fixes #969.
- Replace language detection package: from `langdetect` to `langid`
- Trigger multiprocessing usage only for dataset size bigger than some cutoff (`n_rows * n_cols >= 1e4` by default)
- For the dataframe in the issue above: `0.08 [s]` before, `0.007 [s]` after.
- For [`stack_overflow_survey`](https://github.com/mindsdb/benchmarks/blob/main/benchmarks/datasets/stack_overflow_survey/data.csv) dataset: `84.9 [s]` before, `46.4 [s]` after.

Faster type inference

---

lightwood/data/timeseries_transform.py
lightwood/mixer/sktime.py
tests/integration/advanced/test_timeseries.py

Fixes #959.
- Drop duplicate entries for every partition when transforming any time series input.
- Also fixes a small issue computing trial losses inside the `sktime` mixer, plus additional TS tests for coverage.
- We may want to do aggregation in the future (see #959 and other issues referenced there). If so, an alternate approach may be better. For now, though, discussions have led to a design where resampling happens in the data layer rather than lightwood, so it's less important to have `resample`/`reduce` for the time being.

Deduplicate entries in TS transform

---

lightwood/analysis/explain.py
lightwood/api/json_ai.py
lightwood/api/types.py
lightwood/data/statistical_analysis.py
lightwood/helpers/ts.py
requirements.txt
tests/integration/advanced/test_timeseries.py

Fixes #910 
Uses `pydatainfer` to store the originally observed datetime format for the `tss.order_by` column.
User can specify `time_format` inside prediction arguments as follows:
- left unspecified results in unix epoch for timestamps (default behavior)
- `infer` will use the format inferred from a training dataset sample
- any other string can be used as input if a different/custom format is preferred

[Fix] #910: original format in order column

---

lightwood/analysis/helpers/shap.py
tests/unit_tests/analysis/test_shap.py

Fixes #978 
Ensuring the block only uses valid input columns. Additionally, moved base and final response to be additional columns in the output rows.

[Fix] SHAP block uses original input columns only

---

lightwood/mixer/sktime.py
tests/integration/advanced/test_timeseries.py

Fixes inconsistency in sktime-based mixer usage from MindsDB, where the `forecast_offset` argument was not being set.
The setting of `forecast_offset` is now automatic, and performed based on a few things:
- latest observed timestamp at training, per time series
- inferred frequency of each time series
- first observed timestamp when emitting forecasts, per time series
We should change the `infer_mode` setting to be done with a simple boolean flag. As it's not needed anymore after this change.

Infer offset in SkTime mixers

---

.gitignore
lightwood/mixer/__init__.py
requirements.txt
requirements_extra_ts.txt
requirements_prophet.txt

To keep default installation dependencies manageable.
Any users that want to use either of these mixers will have to `pip install lightwood[extra_ts]`.

Remove n-hits & prophet from default mixer list

---

lightwood/api/json_ai.py
tests/integration/basic/test_regression.py

fixes #1010 
As explained in #1011 the versioning logic will be added in code generation phase.

Add lightwood library version to predictor

---

lightwood/analysis/analyze.py
lightwood/api/json_ai.py
lightwood/api/types.py
lightwood/helpers/general.py
lightwood/helpers/ts.py

Improves UX in forecasting scenarios by using a more streamlined accuracy function and mixer evaluation procedure.
- New evaluation protocol for TS predictors: now only the first forecast horizon is considered for accuracy computation. If there are multiple series (i.e. groups), the first data point for each is used.
- New complementary sMAPE metric is now the default metric in forecasting use cases.

Simpler TS evaluation

---

lightwood/api/json_ai.py
lightwood/api/types.py
tests/integration/basic/test_jsonai.py

The type inference engine is not perfect. And even then, it should be possible for a user to override the inferred type for any reason whatsoever. So far, it wasn't possible, but this PR fixes that.
Adds a `dtype_dict` field to the `ProblemDefinition` class to enable the override. At JsonAI building time, we iterate over the specified keys and replace any inferred types with the user definied ones.

feat: override inferred types

---

lightwood/api/json_ai.py
lightwood/api/types.py
lightwood/data/timeseries_transform.py
tests/integration/advanced/test_timeseries.py

This PR adds a prediction argument (`force_ts_infer`) that modifies the behavior of predict calls in time series models so that an additional row is provided in the returned data frame, corresponding to the first out of sample forecast w.r.t. the passed input.
Fixes #990 and #1055.

Force infer_row in bulk ts predictions

---

lightwood/api/types.py
lightwood/ensemble/stacked_ensemble.py
lightwood/ensemble/ts_stacked_ensemble.py
lightwood/ensemble/weighted_mean_ensemble.py

Adds a `mixer_weights` parameter to prediction arguments in order to control the composition of a prediction for ensembles with numerical targets that have a pre-learnt weight vector.

[ENH] Dynamic mixer weights for numerical ensembles

---

lightwood/ensemble/best_of.py
lightwood/mixer/gluonts.py

Helps with mixers that are very expensive to run, e.g. GluonTS.
This way, we can override model prediction on a (potentially huge) validation dataset and simply report the validation loss as a proxy, for example. It's up to the provided function that will override the specified mixer within the ensemble.

[feat] add special dispatch for bestof ensemble

---

.github/workflows/ligthtwood.yml
.github/workflows/release.yml
README.md
setup.py

Needed as we move towards PyTorch 2.0 (see #1130).

Deprecate support for Python 3.7

---

lightwood/mixer/nhits.py

This PR sets the default value of early stopping to 10 epochs, which should be enough to avoid unnecessarily long training times if the loss has flatlined.

[nhits] early stop by default

---

lightwood/analysis/analyze.py
lightwood/api/json_ai.py
lightwood/data/encoded_ds.py
lightwood/helpers/ts.py
lightwood/mixer/random_forest.py

- `RandomForestMixer`: reduce number of hyperparameter search trials from 20 to 5
- Rename `filter_ds` to `filter_ts`. Change signature and usage so that it directly interacts with `pd.DataFrame`s instead.
- Setting up a cache in the generated `Predictor` code that maintains three `EncodedDs` objects through the `learn()` pipeline, deleting them at the end to avoid bloated binaries. This helps reduce the number of instantiations, as all invocations are done through `featurize()`, which checks (and potentially uses) the cache first.
- Avoid duplicate instantiation of validation `EncodedDs` object inside `analysis`, reverting to use the predictor's cache instead.
This reduces `learn()` runtime anywhere from 15% to 50% depending on the dataset and predictor properties.

[ENH] Top level cache for Predictor.featurize()

---

lightwood/encoder/text/pretrained.py

Note: this builds on top of #1145 so the PR is set against that branch. However, it should be merged into `staging` eventually!
Refactored `PretrainedTextEncoder` training loop to introduce a few things that could help with getting a better runtime-accuracy tradeoff by default:
1. Create and use a validation split.
2. Early stopping strategies based on validation and training loss.
3. Replaced a few operations for vectorized equivalents.
Tests indicate a further 15% improvement compared to #1145 in text classification tasks that use the UnitMixer

[ENH] faster pretrained text encoder

---

lightwood/analysis/helpers/feature_importance.py
lightwood/api/json_ai.py
lightwood/data/encoded_ds.py
lightwood/encoder/array/ts_num_array.py
lightwood/encoder/categorical/onehot.py
lightwood/encoder/numeric/numeric.py
lightwood/encoder/numeric/ts_numeric.py
lightwood/encoder/text/short.py
lightwood/mixer/neural.py
lightwood/mixer/neural_ts.py
lightwood/mixer/random_forest.py
lightwood/mixer/regression.py
requirements_image.txt
tests/unit_tests/encoder/numeric/test_numeric.py

1. `EncodedDs.__getitem__` now retrieves rows from an "offline" cache that is populated at the end of the initialization method, instead of just-in-time. This enables encoders (which are assumed to be optimized, mostly there but some exceptions we're working on at the moment) to do batch encoding at a much faster rate.
2. Optimized some encoders with vectorized operations (see point 1): `NumericalEncoder`, `TsNumericEncoder`, `TsArrayNumericEncoder`
3. Reactivated Neural mixer's early stopping with a patience-based mechanism, and a learning rate search procedure with a standard range of options.
4. Deactivated RandomForest mixer's hyperparam optimization by default due to small loss in accuracy traded by a large speedup in training runtime.
Lightwood becomes an order of magnitude faster …

[ENH] Offline batching

---

lightwood/__about__.py
lightwood/encoder/categorical/binary.py
requirements.txt
tests/unit_tests/encoder/categorical/test_binary.py

The reason for this: due to sampling, categorical columns with weird distributions can be seen as binary by `type_infer`. This isn't really a bug, it's the nature of using samples for type inference. This happened recently during internal testing with the OpenML "micro mass" dataset.
Anyway, if this edge case triggers, our current implementation of the binary encoder will fail. This PR adds a slight fix so that it doesn't. The new (unseen) classes won't really map out to anything, so the user is still nudged towards overriding and using a multiclass encoder, but at least the predictor is able to finish training successfully.

[ENH] Handle n_classes > 2 in binary encoder as unknowns

---

lightwood/data/timeseries_transform.py
lightwood/encoder/datetime/datetime.py
tests/integration/advanced/test_timeseries.py
tests/unit_tests/encoder/date/test_datetime.py

Fixes #891.
Additionally, this encoder is now able to end-to-end encode and decode 20 million rows in less than 40 seconds with consumer hardware.

[fix] Optimized datetime encoder

---

lightwood/data/timeseries_transform.py

Apply `.astype` to part of array is much slower, then to full array. This little change fix it. Depend on count of groups, speedup of model learn in % is about:
```
+------+-------+------+
|  50  |  100  | 500  |
+------+-------+------+
| 53.8 | 7.77  | 4.88 |
+------+-------+------+
```

Improve `transform_timeseries`

---

lightwood/analysis/explain.py
lightwood/api/json_ai.py
lightwood/helpers/log.py
lightwood/helpers/ts.py
lightwood/mixer/nhits.py

Changelog:
- Refactored `helpers.ts.get_inferred_timestamps()` to strictly use vectorized operations.
- Refactored `mixer.nhits.__call__()` to strictly use vectorized operations.
- Improved predictor time logging: `@timed` becomes `@timed_predictor`, and we introduce `timed` for logging arbitrary calls to the logger's stream.
- Added timed call to the ensemble section for `DEBUG` levels.

[ENH] Efficient TS predict

---

.flake8
.github/workflows/ligthtwood.yml
lightwood/data/timeseries_transform.py
lightwood/mixer/gluonts.py
requirements.txt
requirements_extra_ts.txt
setup.py
tests/integration/advanced/test_timeseries.py

This PR bumps a few packages to enable support for 3.10 and 3.11 (without having to compile any packages for which binaries are available).

Add support for Python 3.10 & 3.11

---

lightwood/helpers/device.py
lightwood/helpers/torch.py

Improve documentation of device-related methods and docs regarding GPU usage

---

lightwood/api/types.py

In response to [mdb_evaluator#32](https://github.com/mindsdb/mindsdb_evaluator/pull/32).
Users can now do:
```python
jai = json_ai_from_problem(train_df,
ProblemDefinition.from_dict({'target': TARGET}))
jai.accuracy_functions = [{'module': 'precision_score', 'args': {'average': 'macro'}}]
```
To control the arguments passed into sklearn metrics.

fix type hint

---

MANIFEST.in

Fixes issues with torchvision missing from mindsdb docker files
Extras requirements files are not included in the lightwood pip package, so setup.py can't enumerate them, and when users install e.g. `lightwood[all_extras]` there are packages missing

Include extras requirements files

---

lightwood/api/predictor.py
lightwood/helpers/codegen.py
lightwood/helpers/constants.py
tests/integration/basic/test_categorical.py

Fixes #988.
Note: This depends on the new release from `mindsdb_evaluator` (0.0.12).
Pending:

[ENH] Add test method to lightwood predictors

---

.github/workflows/doc_build.yml
pyproject.toml

This release marks the first update in 5 months, transitioning from version 24.5.2.1 to 24.11.4.0. Due to the extended timeline, latest version updates are the same as 24.5.2.1(which was not officially published on PyPi). For a detailed overview of the changes included in this release, please refer to the [old release notes](https://github.com/mindsdb/lightwood/pull/1232).
>NOTE: The benchmark tests are not working because the DB is shutdown. This will be fixed for the next release

Release 24.11.4.0

---

.github/workflows/lightwood.yml
poetry.lock
pyproject.toml

This PR removes support for Python 3.8. This has been raised mainly as a requirement for [this](https://github.com/mindsdb/lightwood/pull/1238), however, it makes sense at this point to remove support for 3.8.

Removed Support for Python 3.8

---

lightwood/__about__.py
lightwood/encoder/text/pretrained.py
pyproject.toml

This [PR](https://github.com/huggingface/transformers/pull/36177) from the `transformers` package removes their own implementation of `AdamW` and suggests the use of the version from `torch`.
Fixes https://linear.app/mindsdb/issue/BE-822/fix-broken-lightwood
This PR updates the import in `lightwood` to come from `torch`.

Fixed the AdamW Import Error
